sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLZSPPT8gG3LPW64
    access-key-secret: U6k1br0Z8ga0IXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6397